metadata: /path/to/metadata_Hela_Hek293T.txt
seq_data_folder: /path/to/MinKnow_experiment_folder/
genome_fasta: /path/to/Homo_sapiens.GRCh38.dna.primary_assembly.fa
transcriptome_fasta: /path/to/gencode.v40.transcripts.fa
genome_gtf: /path/togencode.v40.primary_assembly.annotation.gtf
bed_file: /path/tohg38_GENCODE.v38.bed
output_dir: /path/to/output_dir/
barcoded: 1
batchsize: 5
drs: 1
threads: 4
suffix: ""
sample_names: []
